global:
  slack_api_url: https://hooks.slack.com/services/your-slack-hook-uri-here
route:
  # The root route must not have any matchers as it is the entry point for
  # all alerts. It needs to have a receiver configured so alerts that do not
  # match any of the sub-routes are sent to someone.
  receiver: 'team-slack'

  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  group_by: ['group']

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: ${alertmanager.group_wait}

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: ${alertmanager.group_interval}

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 24h

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.

receivers:
- name: 'team-slack'
  slack_configs:
  - channel: '${alertmanager.slack_configs.channel}'
    send_resolved: true