groups:
- name: alert.rules
  rules:
  - alert: instance_down
    expr: up == 0
    for: 1m
    labels:
      severity: page
    annotations:
      description: '{{$labels.instance}} of job {{$labels.job}} has been down for
        more than 1 minutes.'
      summary: Instance {{$labels.instance}} down
  - alert: probe_failure
    expr: probe_success == 0
    for: 5m
    labels:
      severity: page
    annotations:
      description: '{{$labels.instance}} of job {{$labels.job}} has been down for
        more than 5 minutes.'
      summary: Instance {{$labels.instance}} down