modules:
    tcp_connect:
      prober: tcp
      timeout: 5s
      tcp:
        preferred_ip_protocol: "ip4"
    http_2xx:
      prober: http
      timeout: 10s
      http:
        method: GET
        preferred_ip_protocol: "ip4"