server:
  port: 8003
  context-path: ${ixortalk.server.mailing-service.context-path}

spring:
  mail:
    host: yoursmtphost.com
    port: 587
    username: username
    password: password
  thymeleaf:
    mode: HTML5
    prefix: ${spring.cloud.config.uri}/ixortalk.mailing.service/default/master/templates/
    check-template: false

ixortalk:
  mail:
    from: no-reply@yourdomain.com
  messages:
    basename: ${spring.cloud.config.uri}/ixortalk.mailing.service/default/master/i18n/messages

logging:
  level:
    # Setting log level to DEBUG to have mail content in log file
    com.ixortalk.mailing.service.send: DEBUG