server:
  port: ${ixortalk.server.mailing-service.port}
  context-path: ${ixortalk.server.mailing-service.context-path}

management:
  port: 8503

spring:
  mail:
    host: yoursmtphost.com
    port: 587
    username: username
    password: password
  thymeleaf:
    mode: HTML5
    check-template: false

ixortalk:
  mail:
    from: no-reply@yourdomain.com

logging:
  level:
    # Setting log level to DEBUG to have mail content in log file
    com.ixortalk.mailing.service.send: DEBUG