server:
  port: 8001
  context-path: ${ixortalk.server.assetmgmt.context-path}

spring:
  data:
    mongodb:
      uri: mongodb://fix_me

assetmgmt:
  schemas:
    asset: ${spring.cloud.config.uri}/ixortalk.assetmgmt/${spring.profiles.active}/master/schemas/asset-schema.json

ixortalk:
  prometheus:
    static-configs-path: /assets
    write-static-configs-interval-milliseconds: 60000
    scrape:
      config:
        host-property-name: hostname
        port-property-name: port